import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {api} from '../server/api.mjs';
const L=globalThis.IEE_LEARNING;
function db(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_perpetual_robbie_robertson.sql',import.meta.url),'utf8'));return {prepare(query){return {bind(...args){return {async first(){return sql.prepare(query).get(...args)||null},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:r.changes}}}}}}},close(){sql.close()}}}
function req(method='GET',user='alice',body=null,origin='https://example.test'){return new Request('https://example.test/api/progress',{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),'Content-Type':'application/json',Origin:origin},...(body?{body:JSON.stringify(body)}:{})})}
const write=(progress=L.blank(),revision=0,writeId='write-1')=>({progress,revision,writeId});
test('anonymous, cross-origin and invalid payload requests cannot write',async()=>{const DB=db();assert.equal((await api(req('GET',null),{DB})).status,401);assert.equal((await api(req('PUT','alice',write(),'https://evil.test'),{DB})).status,403);assert.equal((await api(req('PUT','alice',write({schemaVersion:2})),{DB})).status,422);assert.equal((await api(req('GET','alice'),{DB})).status,200);DB.close()});
test('two users are isolated even when body claims another user',async()=>{const DB=db();const payload=write();payload.userId='bob';payload.progress.preferences.level='Alice';assert.equal((await api(req('PUT','alice',payload),{DB})).status,200);const bob=await (await api(req('GET','bob'),{DB})).json();assert.equal(bob.progress,null);const alice=await (await api(req('GET','alice'),{DB})).json();assert.equal(alice.progress.preferences.level,'Alice');DB.close()});
test('parallel writes conflict and same request retry is idempotent',async()=>{const DB=db();const results=await Promise.all([api(req('PUT','alice',write(L.blank(),0,'one')),{DB}),api(req('PUT','alice',write(L.blank(),0,'two')),{DB})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const remote=await (await api(req('GET'),{DB})).json();const retry=await (await api(req('PUT','alice',write(L.blank(),0,remote.writeId)),{DB})).json();assert.equal(retry.revision,1);assert.equal((await api(req('PUT','alice',write(L.blank(),1,'next')),{DB})).status,200);assert.equal((await api(req('PUT','alice',write(L.blank(),1,'stale')),{DB})).status,409);DB.close()});
test('server derives scores and reviews instead of trusting client aggregates',async()=>{const DB=db();let p=L.blank();p.reviews={fake:{state:'Maîtrisé',successes:99}};let r=await api(req('PUT','alice',write(p)),{DB});assert.equal(r.status,200);const stored=await (await api(req(),{DB})).json();assert.deepEqual(stored.progress.reviews,{});const at=new Date().toISOString();p=L.start(L.blank(),'s1',at);p.active.step=5;p.active.memo=1;p.active.attempts=[{id:'a1',skill:'mémoriser',answer:'wrong',correct:true,hint:false,at}];p=L.complete(p,at);r=await api(req('PUT','alice',write(p,1,'invalid')),{DB});assert.equal(r.status,422);DB.close()});
test('valid legacy session imports with recomputed spaced reviews',async()=>{const DB=db();const at='2026-09-11T12:00:00.000Z';let p=L.start(L.blank(),'legacy',at);p.active.step=5;p.active.memo=1;let n=0;for(const [skill,answer] of [['comprendre','1'],['texte à trous','pain parole'],['mémoriser',L.lesson.text],['retrouver','Matthieu 4:4'],['appliquer','1']])p=L.attempt(p,{id:'a'+n++,skill,answer,correct:true,hint:false,now:at});p=L.complete(p,at);assert.equal((await api(req('PUT','alice',write(p)),{DB})).status,200);const stored=await (await api(req(),{DB})).json();assert.equal(stored.progress.sessions.length,1);assert.equal(stored.progress.reviews[L.lesson.id].state,'En apprentissage');DB.close()});
test('database errors are explicit and responses never cache private data',async()=>{assert.equal((await api(req(),{})).status,503);const r=await api(req(),{DB:{prepare(){throw Error('down')}}});assert.equal(r.status,503);assert.match(r.headers.get('cache-control'),/no-store/)});
