import {test} from 'node:test';import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';
import {ProgressRepository} from '../portable/postgres.mjs';
import {normalizeProgress} from '../server/state.mjs';
const L=globalThis.IEE_LEARNING;
const alice={id:'11111111-1111-4111-8111-111111111111',subject:'alice',provider:'test'};
const bob={id:'22222222-2222-4222-8222-222222222222',subject:'bob',provider:'test'};
async function setup(){const db=new PGlite();await db.exec(readFileSync(new URL('../migrations/postgres/001_accounts.sql',import.meta.url),'utf8'));await db.exec('SET ROLE iee_app');const pool={async connect(){return {query:(...a)=>db.query(...a),release(){}}}};return {db,repo:new ProgressRepository(pool)};}
function session(){const at='2026-09-11T12:00:00.000Z';let p=L.start(L.blank(),'legacy',at);p.active.step=5;p.active.memo=1;let n=0;for(const [skill,answer] of [['comprendre','1'],['texte à trous','pain parole'],['mémoriser',L.lesson.text],['retrouver','Matthieu 4:4'],['appliquer','1']])p=L.attempt(p,{id:'a'+n++,skill,answer,correct:true,hint:false,now:at});return normalizeProgress(L.complete(p,at));}
test('PostgreSQL RLS blocks cross-user reads and writes independently of API',async()=>{const {db,repo}=await setup();try{await repo.save(alice,normalizeProgress(L.blank()),0,'one');await repo.save(bob,normalizeProgress(L.blank()),0,'two');await db.query("SELECT set_config('iee.user_id',$1,false)",[alice.id]);assert.equal((await db.query('SELECT user_id FROM iee.progress')).rows.length,1);assert.equal((await db.query('SELECT * FROM iee.progress WHERE user_id=$1',[bob.id])).rows.length,0);const q=await db.query('UPDATE iee.progress SET revision=99 WHERE user_id=$1 RETURNING revision',[bob.id]);assert.equal(q.rows.length,0);await assert.rejects(db.query('INSERT INTO iee.learning_sessions(user_id,id,lesson_id,completed_at,evidence) VALUES($1,$2,$3,now(),$4)',[bob.id,'bad','mat','{}']),/row-level security/i);}finally{await db.close()}});
test('PostgreSQL stores normalized history, refuses stale writes and keeps completed sessions immutable',async()=>{const {db,repo}=await setup();try{const p=session();assert.equal((await repo.save(alice,p,0,'one')).revision,1);assert.equal((await repo.save(alice,p,0,'one')).revision,1);assert.equal((await repo.save(alice,p,0,'stale')).error,'revision_conflict');const read=await repo.load(alice);assert.equal(read.progress.sessions.length,1);assert.equal((await repo.save(alice,normalizeProgress(L.blank()),1,'erase')).error,'history_conflict');const altered=structuredClone(p);altered.sessions[0].attempts[0].answer='changed';assert.equal((await repo.save(alice,altered,1,'alter')).error,'history_conflict');assert.equal((await repo.save(alice,p,1,'two')).revision,2);await db.query("SELECT set_config('iee.user_id',$1,false)",[alice.id]);assert.equal((await db.query('SELECT * FROM iee.learning_attempts')).rows.length,5);}finally{await db.close()}});
