const {test}=require('node:test');const assert=require('node:assert/strict');
const Sync=require('../dist/assets/sync.js');const L=require('../dist/assets/learning.js');
function storage(){const map=new Map();return {map,getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)}}
function remote(user='alice'){let state=null,revision=0,id=null;const fetch=async(url,options={})=>{if(url==='/api/account')return Response.json({id:user,email:user+'@test'});if(options.method==='PUT'){const b=JSON.parse(options.body);if(b.revision!==revision)return Response.json({}, {status:409});state=b.progress;revision++;id=b.writeId;return Response.json({revision,writeId:id,updatedAt:new Date().toISOString()});}return Response.json({progress:state,revision,writeId:id});};return {fetch,setRevision:r=>revision=r,get revision(){return revision}};}
const tick=()=>new Promise(r=>setImmediate(r));
test('network failure retains pending data and retry stores it once',async()=>{const st=storage(),r=remote();let fail=false;const s=new Sync(st,async(u,o)=>{if(fail&&o?.method==='PUT')throw Error('offline');return r.fetch(u,o)},()=>{});await s.open();fail=true;s.enqueue(L.blank());await tick();assert.ok(s.pending);fail=false;await s.flush();assert.equal(s.pending,null);assert.equal(r.revision,1)});
test('pending changes from another account are never imported',async()=>{const st=storage();st.setItem('iee-account-v1:alice',JSON.stringify({revision:0,pending:{writeId:'x',progress:L.blank()}}));const s=new Sync(st,remote('bob').fetch,()=>{});const result=await s.open();assert.equal(result.progress,null);assert.equal(s.pending,null);assert.ok(st.getItem('iee-account-v1:alice'))});
test('concurrent-device conflict blocks overwrite and keeps a recovery copy',async()=>{const st=storage(),r=remote(),statuses=[];const s=new Sync(st,r.fetch,x=>statuses.push(x));await s.open();r.setRevision(1);s.enqueue(L.blank());await tick();assert.ok(s.conflict);assert.ok(s.pending);assert.ok(statuses.includes('conflict'));await s.useServer();assert.equal(s.conflict,false);assert.ok([...st.map.keys()].some(x=>x.includes(':recovery:')))});
test('reload recovers a pending write without changing its id',async()=>{const st=storage(),r=remote();st.setItem('iee-account-v1:alice',JSON.stringify({revision:0,pending:{writeId:'stable',progress:L.blank()}}));const s=new Sync(st,r.fetch,()=>{});const result=await s.open();assert.ok(result.progress);await tick();assert.equal(s.pending,null);assert.equal(r.revision,1)});
